Fix SQL Error in Logged Topic
Log the Exception in AbstractTopicsDbMigrator instead of throw the
error: https://b.corp.google.com/issues/294298868#comment16

Test: atest DbHelperTest AbstractTopicsDbMigratorTest

Bug: 294298868

Change-Id: Ieaeece2b82057eafed665e573ba1354aaaacba2a