Fix SQL Error in Logged Topic
Log the Exception in AbstractTopicsDbMigrator instead of throw the
error: https://b.corp.google.com/issues/294298868#comment16

Test: atest DbHelperTest AbstractTopicsDbMigratorTest

Bug: 294298868
(cherry picked from https://googleplex-android-review.googlesource.com/q/commit:c95e9b01df70b53d1a40e92545087b8113d128b2)
Merged-In: Ieaeece2b82057eafed665e573ba1354aaaacba2a
Change-Id: Ieaeece2b82057eafed665e573ba1354aaaacba2a