Introducing SafeAndroidJUnitRunner.
This runner ignores (some) errors when scanning a test class, like
NoClassDefFoundError when scanning methods that reference an Android
SDK class that is not available in that device's SDK level.

Bug: 323197304
Test: atest OutcomeReceiverForTestsTest # on R, coming soon!

Change-Id: I1eda71817f69bfd3e07218979b92584708bca666