Changed AdServicesFlagsSetterRule so it doesn't throw clean-up errors.
Ideally they should, but we better wait until the rule itself has
unit tests to avoid confusion in corner-cases. In fact, the current
code is wrapping the real exception. Example:

com.android.adservices.tests.cts.endtoendtest (1 Test)
[1/1] com.android.adservices.tests.cts.topics.TopicsManagerTest#testTopicsManager_runOnDeviceClassifier: FAILED (15.284s)

STACKTRACE:
java.lang.RuntimeException: 1 errors finalizing infra: [java.lang.IllegalStateException: D'OH!]
	at com.android.adservices.common.AdServicesFlagsSetterRule$1.evaluate(AdServicesFlagsSetterRule.java:106)


Bug: 294423183
Test: atest CtsAdServicesEndToEndTests:TopicsManagerTest

Change-Id: Ib3b2f13a98ad85100d45700275b89fa3a8cf14dd