Fixed build breakage caused by ag/19245595
Error: https://android-build.googleplex.com/builds/submitted/8828140/test_suites_arm64/latest/view/logs/build_error.log

Bug: 238934907

Test: atest AdServicesFrameworkUnitTests && atest
AdServicesServiceCoreUnitTests

Change-Id: I235aa737b722546a83803f719993a9837f7ad1f5